# Change these first
owner: RJD111 # Your GitHub organization or username, where this repository lives
repo: IEO-Uptime # The name of this repository

sites:
  - name: Melbury Office
    url: $MELBURYOFFICE
  - name: Gates at Lions Lodge
    url: $GATESLIONSLODGE
  - name: Melbury House test
    check: "tcp-ping"
    url: 185.67.235.5
    port: 53
  - name: Google DNS
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: ieouptime.dixonservers.co.uk
  #baseUrl: /IEO-Uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: IEO Uptime
  introTitle: "**Ilchester Estates - Internet Connections**"
  introMessage: This page will display uptime information on all IEO internet connections
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
